# Extraction of the location of RES time series for the Nord_H2ub Spine Model

This file extracts the geographical centres of the bidding zones of the Nordics.

The locations are then used to get the time series of onshore wind and PV. 

**Authors**: Johannes Giehl (jfg.eco@cbs.dk)

In [4]:
import geopandas as gpd

In [5]:
def add_geographic_center(shape_gdf):
    """Adds a geographic center column to the GeoDataFrame."""
    # Reproject to a projected coordinate system (EPSG:3035 for Europe)
    shape_gdf = shape_gdf.to_crs(epsg=3035)
    
    # Calculate centroids in the projected CRS (in meters)
    shape_gdf['centroid'] = shape_gdf.geometry.centroid
    
    # Reproject centroids to geographic coordinates (EPSG:4326) to account for Earth's curvature
    shape_gdf['geographic_center'] = shape_gdf['centroid'].to_crs(epsg=4326)
    
    # Ensure the 'geographic_center' column is a GeoSeries with the correct CRS (EPSG:4326)
    shape_gdf['geographic_center'] = gpd.GeoSeries(shape_gdf['geographic_center'], crs='EPSG:4326')

    return shape_gdf.drop(columns=['centroid'])

In [8]:
bidding_zones_gdf = gpd.read_file('world.geojson')

In [9]:
nordic_countries = ["SE", "NO", "FI", "DK"]
nordic_bidding_zones_gdf = bidding_zones_gdf[bidding_zones_gdf["countryKey"].isin(nordic_countries)]
nordic_bidding_zones_gdf

,zoneName,countryKey,countryName,geometry
0,SE-SE4,SE,Sweden,"MULTIPOLYGON (((12.37512 56.91149, 12.35227 56..."
1,SE-SE3,SE,Sweden,"MULTIPOLYGON (((18.56359 60.22731, 18.32958 60..."
2,SE-SE2,SE,Sweden,"MULTIPOLYGON (((20.30960 63.65475, 20.07200 63..."
3,SE-SE1,SE,Sweden,"MULTIPOLYGON (((16.38861 67.04356, 16.40663 67..."
78,DK-DK1,DK,Denmark,"MULTIPOLYGON (((9.43749 54.81066, 9.58510 54.9..."
79,DK-DK2,DK,Denmark,"MULTIPOLYGON (((11.85312 55.73228, 11.66232 55..."
80,DK-BHM,DK,Denmark,"MULTIPOLYGON (((15.15075 55.13265, 14.76195 55..."
101,FI,FI,Finland,"MULTIPOLYGON (((28.92946 69.05084, 28.45648 68..."
212,NO-NO1,NO,Norway,"MULTIPOLYGON (((10.38790 59.55041, 10.65791 59..."
213,NO-NO2,NO,Norway,"MULTIPOLYGON (((5.27945 59.29281, 5.20745 59.4..."
214,NO-NO3,NO,Norway,"MULTIPOLYGON (((12.29826 62.26430, 12.05744 62..."
215,NO-NO4,NO,Norway,"MULTIPOLYGON (((29.04194 69.01076, 29.24129 69..."
216,NO-NO5,NO,Norway,"MULTIPOLYGON (((8.40428 61.48237, 7.29547 61.8..."

In [10]:
nordic_bidding_zones_gdf = add_geographic_center(nordic_bidding_zones_gdf)

In [11]:
nordic_bidding_zones_gdf

,zoneName,countryKey,countryName,geometry,geographic_center
0,SE-SE4,SE,Sweden,"MULTIPOLYGON (((4465799.535 3758920.229, 44640...",POINT (14.38223 56.57230)
1,SE-SE3,SE,Sweden,"MULTIPOLYGON (((4795506.128 4153909.839, 47818...",POINT (14.79368 59.33349)
2,SE-SE2,SE,Sweden,"MULTIPOLYGON (((4832257.135 4543349.364, 48203...",POINT (15.96231 63.55362)
3,SE-SE1,SE,Sweden,"MULTIPOLYGON (((4601193.835 4893744.424, 46001...",POINT (20.07969 66.71608)
78,DK-DK1,DK,Denmark,"MULTIPOLYGON (((4284821.245 3522910.470, 42943...",POINT (9.46760 56.14205)
79,DK-DK2,DK,Denmark,"MULTIPOLYGON (((4437474.239 3626822.935, 44250...",POINT (11.83856 55.39782)
80,DK-BHM,DK,Denmark,"MULTIPOLYGON (((4649346.762 3570333.742, 46232...",POINT (14.90690 55.13830)
101,FI,FI,Finland,"MULTIPOLYGON (((5073800.407 5206903.675, 50604...",POINT (26.18841 64.26078)
212,NO-NO1,NO,Norway,"MULTIPOLYGON (((4342988.792 4050032.263, 43582...",POINT (10.70653 60.88882)
213,NO-NO2,NO,Norway,"MULTIPOLYGON (((4051641.375 4030284.872, 40485...",POINT (7.65044 59.19014)
214,NO-NO3,NO,Norway,"MULTIPOLYGON (((4440859.114 4353358.984, 44270...",POINT (9.04236 62.76781)
215,NO-NO4,NO,Norway,"MULTIPOLYGON (((5079481.605 5203895.024, 50836...",POINT (19.82349 68.50716)
216,NO-NO5,NO,Norway,"MULTIPOLYGON (((4235673.330 4265566.028, 41780...",POINT (7.20877 60.76178)